# Generated by Django 5.1.3 on 2024-11-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('teacher', '0002_teacher_models_tdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_models',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_models_FK', to='courses.course_models'),
        ),
    ]
