# Generated by Django 5.1.3 on 2024-11-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_models',
            name='Course_name',
            field=models.CharField(choices=[('ComputerScience', 'ComputerScience'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], max_length=100),
        ),
    ]
