# Generated by Django 5.1.3 on 2024-11-27 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grade_FK', to='courses.course_models')),
            ],
            options={
                'db_table': 'Student_grades',
            },
        ),
        migrations.CreateModel(
            name='Student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=255)),
                ('course_of_studey', models.CharField(blank=True, max_length=255)),
                ('sdelete', models.BooleanField(default=False)),
                ('course', models.ManyToManyField(related_name='Student_Courses_FK', to='courses.course_models')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
