# Generated by Django 5.1.3 on 2024-11-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=255)),
                ('course_of_studey', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
