# Generated by Django 5.1.3 on 2024-11-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_student_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='sdelete',
            field=models.BooleanField(default=False),
        ),
    ]
