# Generated by Django 5.1.3 on 2024-11-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_student_model_sdelete'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='course',
            field=models.ManyToManyField(related_name='Student_Courses_FK', to='courses.course_models'),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='course_of_studey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
