# Generated by Django 5.1.3 on 2024-11-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_model_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='course',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Maths', 'Maths'), ('C Programming', 'C Programming'), ('Computer Science', 'Computer Science')], max_length=255, null=True),
        ),
    ]
