# Generated by Django 5.1.3 on 2024-11-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_model_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
