# Generated by Django 5.1.3 on 2024-11-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_model_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
